AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - "vendor/**/*"
    - "spec/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Max: 20

Layout/LineLength:
  Max: 120
