# frozen_string_literal: true

# BasePlugin defines the interface every plugin must implement.
#
# Plugins can either:
#   1. Subclass BasePlugin and override the abstract methods (code-based).
#   2. Be generated by ConfigPlugin from a YAML definition (config-based).
#
# Required overrides:
#   #name             → String   unique identifier, snake_case
#   #version          → String   SemVer e.g. "1.0.0"
#   #capabilities     → Array<Symbol>  from CAPABILITIES
#   #schema_migrations → Array<Proc>  each proc is a Sequel migration block
#   #routes(r)        → void    mount routes onto the Roda request object
class BasePlugin
  CAPABILITIES = %i[inventory viewer progress stream tagging].freeze

  # Unique snake_case name (must be overridden).
  def name
    raise NotImplementedError, "#{self.class}#name not implemented"
  end

  # SemVer version string (must be overridden).
  def version
    raise NotImplementedError, "#{self.class}#version not implemented"
  end

  # Subset of CAPABILITIES this plugin supports (must be overridden).
  def capabilities
    raise NotImplementedError, "#{self.class}#capabilities not implemented"
  end

  # Array of Sequel migration Procs. Each proc receives the Sequel::Database.
  # Called during plugin load; rolled back on unload.
  # Default: no migrations.
  def schema_migrations
    []
  end

  # Mount plugin-specific routes onto the Roda router.
  # Default: no routes.
  def routes(_r)
    nil
  end

  # Whether this plugin's resources should be auto-tagged by TaggerPlugin.
  # Any plugin that manages inventory (declares :inventory capability) is
  # taggable by default. Pure service plugins (e.g. TaggerPlugin itself)
  # return false and are never auto-tagged.
  def taggable?
    Array(capabilities).include?(:inventory)
  end

  # Called once after the plugin is loaded and its migrations run.
  def on_load; end

  # Called before the plugin is unloaded.
  def on_unload; end

  def to_h
    { name: name, version: version, capabilities: capabilities.map(&:to_s) }
  end
end
